@startuml
nwdiag {
    internet [ shape = cloud ]
    router
    internet -- router

    network public {
        router;
        load_balancer;
    }

    network private {
        load_balancer;  
        cloud_run;      
        database;
    }
}
@enduml