repos:
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      -   id: prettier
          files: '.*\.(ts|tsx)'
          args: ['--parser', 'typescript', '--write']
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.35.0
    hooks:
      -   id: eslint
          files: '.*\.(ts|tsx)'
