@startuml

enum Status {
  running
  succeeded
  failed
}

entity Jobs {
  * id: ULID
  --
  * status: Status
  * created_at: datetime
  * updated_at: datetime
    deleted_at: datetime
}

entity JobFiles {
  * id: ULID
  --
  * job_id: ULID <<FK>>
  * is_output: number
  * file_key: string
  * file_name: string
  * content_type: string
  * size: number
  * width: number
  * height: number
  * created_at: datetime
  * updated_at: datetime
    deleted_at: datetime
}

entity ExtractedTexts {
  * id: ULID
  --
  * job_file_id: ULID <<FK>>
  * text: string
  * top: number
  * bottom: number
  * left: number
  * right: number
  * created_at: datetime
  * updated_at: datetime
    deleted_at: datetime
}

Jobs ||..o{ JobFiles
JobFiles ||..o{ ExtractedTexts

@enduml
