@startuml

enum JobStatus {
  running
  succeeded
  failed
}

enum InputFileStatus {
  running
  succeeded
  failed
}

entity Jobs {
  * id: ULID
  --
  * name: string
  * original_file_key: string
  * status: JobStatus
  * created_at: datetime
  * updated_at: datetime
    deleted_at: datetime
}

entity InputFiles {
  * id: ULID
  --
  * job_id: ULID <<FK>>
  * file_key: string
  * file_name: string
  * content_type: string
  * size: number
  * width: number
  * height: number
  * status: InputFileStatus
  * created_at: datetime
  * updated_at: datetime
    deleted_at: datetime
}

entity OutputFiles {
  * id: ULID
  --
  * job_id: ULID <<FK>>
  * input_file_id: ULID <<FK>>
  * file_key: string
  * file_name: string
  * content_type: string
  * size: number
  * width: number
  * height: number
  * created_at: datetime
  * updated_at: datetime
    deleted_at: datetime
}

entity ExtractedTexts {
  * id: ULID
  --
  * job_id: ULID <<FK>>
  * input_file_id: ULID <<FK>>
  * output_file_id: ULID <<FK>>
  * text: string
  * top: number
  * bottom: number
  * left: number
  * right: number
  * created_at: datetime
  * updated_at: datetime
    deleted_at: datetime
}

Jobs ||..o{ InputFiles
InputFiles ||..ro{ OutputFiles
OutputFiles ||..do{ ExtractedTexts

@enduml
