repos:
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.51.0
    hooks:
      -   id: golangci-lint
          files: '^backend/.*\.go'
          entry: golangci-lint run --fix ./...
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      -   id: prettier
          files: '^frontend/.*\.(ts|tsx)'
          args: ['--parser', 'typescript', '--write']
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.35.0
    hooks:
      -   id: eslint
          files: '^frontend/.*\.(ts|tsx)'
