version: '3.9'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    platform: linux/x86_64
  app:
    container_name: app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    volumes:
      - ./backend/migration:/app/migration
    platform: linux/x86_64
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    platform: linux/x86_64

volumes:
  db-data: