version: '3.9'
services:
  app:
    container_name: app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    env_file:
#      - .env
    platform: linux/x86_64