repos:
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.51.0
    hooks:
      -   id: golangci-lint
          files: '.*\.(go)'
          entry: golangci-lint run ./...
          pass_filenames: false
