FROM golang:1.20-bullseye

WORKDIR /backend

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download
RUN go install github.com/codegangsta/gin@latest

# Basically, gin takes more time than starting db.
CMD ["gin", "--appPort", "8080", "--port", "4000", "--immediate", "--all"]