FROM golang:1.21-bookworm

RUN apt update && apt install -y libmagickwand-dev
RUN sed -i -E 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml

WORKDIR /backend

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download
RUN go install github.com/codegangsta/gin@latest

# Basically, gin takes more time than starting db.
CMD ["gin", "--appPort", "8080", "--port", "4000", "--immediate", "--all"]