// Code generated by mockery. DO NOT EDIT.

package stubs

import mock "github.com/stretchr/testify/mock"

// hmacKeyDescFunc is an autogenerated mock type for the hmacKeyDescFunc type
type hmacKeyDescFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *hmacKeyDescFunc) Execute(_a0 *storage.hmacKeyDesc) {
	_m.Called(_a0)
}

// newHmacKeyDescFunc creates a new instance of hmacKeyDescFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newHmacKeyDescFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *hmacKeyDescFunc {
	mock := &hmacKeyDescFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
