// Code generated by mockery. DO NOT EDIT.

package stubs

import mock "github.com/stretchr/testify/mock"

// isWriteObjectRequest_FirstMessage is an autogenerated mock type for the isWriteObjectRequest_FirstMessage type
type isWriteObjectRequest_FirstMessage struct {
	mock.Mock
}

// isWriteObjectRequest_FirstMessage provides a mock function with given fields:
func (_m *isWriteObjectRequest_FirstMessage) isWriteObjectRequest_FirstMessage() {
	_m.Called()
}

// newIsWriteObjectRequest_FirstMessage creates a new instance of isWriteObjectRequest_FirstMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsWriteObjectRequest_FirstMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *isWriteObjectRequest_FirstMessage {
	mock := &isWriteObjectRequest_FirstMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
