// Code generated by mockery. DO NOT EDIT.

package stubs

import mock "github.com/stretchr/testify/mock"

// isWriteObjectResponse_WriteStatus is an autogenerated mock type for the isWriteObjectResponse_WriteStatus type
type isWriteObjectResponse_WriteStatus struct {
	mock.Mock
}

// isWriteObjectResponse_WriteStatus provides a mock function with given fields:
func (_m *isWriteObjectResponse_WriteStatus) isWriteObjectResponse_WriteStatus() {
	_m.Called()
}

// newIsWriteObjectResponse_WriteStatus creates a new instance of isWriteObjectResponse_WriteStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsWriteObjectResponse_WriteStatus(t interface {
	mock.TestingT
	Cleanup(func())
}) *isWriteObjectResponse_WriteStatus {
	mock := &isWriteObjectResponse_WriteStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
