// Code generated by mockery. DO NOT EDIT.

package stubs

import mock "github.com/stretchr/testify/mock"

// isWriteObjectRequest_Data is an autogenerated mock type for the isWriteObjectRequest_Data type
type isWriteObjectRequest_Data struct {
	mock.Mock
}

// isWriteObjectRequest_Data provides a mock function with given fields:
func (_m *isWriteObjectRequest_Data) isWriteObjectRequest_Data() {
	_m.Called()
}

// newIsWriteObjectRequest_Data creates a new instance of isWriteObjectRequest_Data. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsWriteObjectRequest_Data(t interface {
	mock.TestingT
	Cleanup(func())
}) *isWriteObjectRequest_Data {
	mock := &isWriteObjectRequest_Data{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
