// Code generated by mockery. DO NOT EDIT.

package stubs

import mock "github.com/stretchr/testify/mock"

// PostPolicyV4Condition is an autogenerated mock type for the PostPolicyV4Condition type
type PostPolicyV4Condition struct {
	mock.Mock
}

// MarshalJSON provides a mock function with given fields:
func (_m *PostPolicyV4Condition) MarshalJSON() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// isEmpty provides a mock function with given fields:
func (_m *PostPolicyV4Condition) isEmpty() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewPostPolicyV4Condition creates a new instance of PostPolicyV4Condition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostPolicyV4Condition(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostPolicyV4Condition {
	mock := &PostPolicyV4Condition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
