// Code generated by mockery. DO NOT EDIT.

package stubs

import (
	mock "github.com/stretchr/testify/mock"
	internal "google.golang.org/api/internal"
)

// storageClientOption is an autogenerated mock type for the storageClientOption type
type storageClientOption struct {
	mock.Mock
}

// Apply provides a mock function with given fields: _a0
func (_m *storageClientOption) Apply(_a0 *internal.DialSettings) {
	_m.Called(_a0)
}

// ApplyStorageOpt provides a mock function with given fields: _a0
func (_m *storageClientOption) ApplyStorageOpt(_a0 *storage.storageConfig) {
	_m.Called(_a0)
}

// newStorageClientOption creates a new instance of storageClientOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newStorageClientOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *storageClientOption {
	mock := &storageClientOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
