// Code generated by mockery. DO NOT EDIT.

package stubs

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	storagepb "cloud.google.com/go/storage/internal/apiv2/storagepb"
)

// Storage_WriteObjectServer is an autogenerated mock type for the Storage_WriteObjectServer type
type Storage_WriteObjectServer struct {
	mock.Mock
}

// Context provides a mock function with given fields:
func (_m *Storage_WriteObjectServer) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// Recv provides a mock function with given fields:
func (_m *Storage_WriteObjectServer) Recv() (*storagepb.WriteObjectRequest, error) {
	ret := _m.Called()

	var r0 *storagepb.WriteObjectRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() (*storagepb.WriteObjectRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *storagepb.WriteObjectRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storagepb.WriteObjectRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecvMsg provides a mock function with given fields: m
func (_m *Storage_WriteObjectServer) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendAndClose provides a mock function with given fields: _a0
func (_m *Storage_WriteObjectServer) SendAndClose(_a0 *storagepb.WriteObjectResponse) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*storagepb.WriteObjectResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendHeader provides a mock function with given fields: _a0
func (_m *Storage_WriteObjectServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMsg provides a mock function with given fields: m
func (_m *Storage_WriteObjectServer) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetHeader provides a mock function with given fields: _a0
func (_m *Storage_WriteObjectServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *Storage_WriteObjectServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// NewStorage_WriteObjectServer creates a new instance of Storage_WriteObjectServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage_WriteObjectServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage_WriteObjectServer {
	mock := &Storage_WriteObjectServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
