// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "github.com/ijufumi/google-vision-sample/internal/models/entities"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// JobRepository is an autogenerated mock type for the JobRepository type
type JobRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: db, entity
func (_m *JobRepository) Create(db *gorm.DB, entity *entities.Job) error {
	ret := _m.Called(db, entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entities.Job) error); ok {
		r0 = rf(db, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: db, id
func (_m *JobRepository) Delete(db *gorm.DB, id string) error {
	ret := _m.Called(db, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) error); ok {
		r0 = rf(db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: db
func (_m *JobRepository) GetAll(db *gorm.DB) ([]*entities.Job, error) {
	ret := _m.Called(db)

	var r0 []*entities.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB) ([]*entities.Job, error)); ok {
		return rf(db)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB) []*entities.Job); ok {
		r0 = rf(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB) error); ok {
		r1 = rf(db)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: db, id
func (_m *JobRepository) GetByID(db *gorm.DB, id string) (*entities.Job, error) {
	ret := _m.Called(db, id)

	var r0 *entities.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) (*entities.Job, error)); ok {
		return rf(db, id)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) *entities.Job); ok {
		r0 = rf(db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, string) error); ok {
		r1 = rf(db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: db, entity
func (_m *JobRepository) Update(db *gorm.DB, entity *entities.Job) error {
	ret := _m.Called(db, entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entities.Job) error); ok {
		r0 = rf(db, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJobRepository creates a new instance of JobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobRepository {
	mock := &JobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
