name: Deploy frontend

on:
  push:
    paths:
      - frontend/
  workflow_dispatch:

env:
  BACKEND_URL: https://vision-sample-api.ijufumi.net/
  S3_BUCKET: vision-sample-bucket
  CLOUDFRONT_DISTRIBUTION_ID: E3DZFR599EHOPW

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'frontend'

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: 'frontend'
        env:
          REACT_APP_ENDPOINT_URL: ${{ env.BACKEND_URL }}/api/v1

      - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: frontend/build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          dist-id: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
