name: Deploy backend

on:
  push:
    paths:
      - backend/
  workflow_dispatch:

env:
  IMAGE_URI: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_REPO_NAME }}/${{ vars.GCP_IMAGE_NAME }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Google auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Build
        run: |
          docker build -t ${{ env.IMAGE_URI }} backend

      - name: Push
        run: |
          docker push ${{ env.IMAGE_URI }}

      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ vars.GCP_CLOUD_RUN_NAME }}
          image: ${{ env.IMAGE_URI }}
