name: Deploy backend

on:
  push:
    paths:
      - backend/
  workflow_dispatch:

env:
  IMAGE_URI: ${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Build
        run: |
          docker build -t ${{ env.IMAGE_URI }} backend

      - name: Push
        run: |
          docker push ${{ env.IMAGE_URI }}